version: "3.9"

services:
  worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ips-data-acquisition-worker
    environment:
      ASPNETCORE_ENVIRONMENT: Docker
      ConnectionStrings__Default: "Host=db;Port=5432;Database=ips_data_acquisition;Username=postgres;Password=postgres"
      RabbitMQ__HostName: rabbitmq
      RabbitMQ__Port: 5672
      RabbitMQ__UserName: guest
      RabbitMQ__Password: guest
      RabbitMQ__QueueName: imu-data-queue
      RabbitMQ__PrefetchCount: 20
      RabbitMQ__MaxConcurrency: 10
    depends_on:
      - db
      - rabbitmq
    restart: unless-stopped

  db:
    image: postgres:16-alpine
    container_name: ips-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ips_data_acquisition
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: ips-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"   # AMQP port
      - "15672:15672" # Management UI
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  postgres_data:
  rabbitmq_data:

